### ISSUE TITLE
downloads stopped working today

### ISSUE THREAD

**Issue by ClaireCJS** [johnwmillr/LyricsGenius#282]
It happened sometime in the last few hours.

I am now getting this:

```
 Searching for "Stress Tabs" by Ween...
          Couldn't find the lyrics section. Please report this if the song has lyrics.
          Song URL: https://genius.com/Ween-stresstabs-lyrics
          Specified song does not have a valid lyrics. Rejecting.
          Could not find specified song. Check spelling?
```

The url is valid. All of a sudden, nothing is getting saved 😢

i spent a month creating a project around this, and just today i hit 99%, and now it doesn’t work at all, lol.

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
@ClaireCJS This should be fixed now!

**Comment by johnwmillr** [comment]
Yes, let me know if you're still running into this issue, @ClaireCJS.

**Comment by emmakrentz** [comment]
I am also still having this issue with every song I try to access.

**Comment by ClaireCJS** [comment]
Fixed how? Is there a new release or something?

**Comment by johnwmillr** [comment]
Yes sorry, I wasn't clear. If you still install to the latest version (3.1.1), there's a fix for this issue.

```
pip install -U lyricsgenius
```

Or pull the latest changes from this repo, and install from there:

```
pip install git+https://github.com/johnwmillr/LyricsGenius.git
```

**Comment by ClaireCJS** [comment]
> Yes sorry, I wasn't clear. If you still install to the latest version (3.1.1), there's a fix for this issue.
> 
> ```
> pip install -U lyricsgenius
> ```
> 
> Or pull the latest changes from this repo, and install from there:
> 
> ```
> pip install git+https://github.com/johnwmillr/LyricsGenius.git
> ```

Thanks!

Alas....


![image](https://github.com/user-attachments/assets/d2b3003a-4f56-47d8-9b48-e70b3b8fc324)

**Comment by johnwmillr** [comment]
Shoot, that looks like an unrelated bug introduced by #276. I opened #285 to track this issue.

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
Oh damn, I just realised I was using @johnwmillr's fixed version when I did my fix, so the circular import was already fixed.

Very sorry, should've noted that!

**Comment by emmakrentz** [comment]
I updated to 3.1.2 but I'm still having the above issue, any advice?

**Comment by emmakrentz** [comment]
updated to 3.1.2 and the fix is working for me! ty

**Comment by ClaireCJS** [comment]
@johnwmillr I think it’s fixed now!
